---

- hosts: all
  become: true
  pre_tasks: 


  - name: install updates for distro(Ubuntu)
    apt:
      update_cache: yes

  - name: install nginx
    apt:
      name: 
        - nginx
      state: latest

  - name: start and enable nginx
    service:
      name: nginx
      state: started
      enabled: yes

